<?xml version="1.0"?>
<package format="3">
  <name>ros2_objectpose</name>
  <version>0.0.0</version>
  <description>IFRA-Cranfield (Cranfield University, UK). Package: IFRA_ObjectPose - ObjectPose GzPlugin (ROS 2)</description>

  <author>Mikel Bueno Viso</author>
  <maintainer email="Mikel.Bueno-Viso@cranfield.ac.uk">Mikel Bueno Viso</maintainer>

  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- ROS 2 deps -->
  <depend>rclcpp</depend>
  <depend>objectpose_msgs</depend>

  <!-- Gazebo Harmonic libraries -->
  <depend>gz-sim8</depend>
  <depend>gz-plugin2</depend>
  <depend>gz-math7</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
